using InsuranceProject.DTOs;
using InsuranceProject.Exceptions;
using InsuranceProject.Helper;
using InsuranceProject.Models;
using InsuranceProject.Services;
using InsuranceProject.Types;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace InsuranceProject.Controllers
{

    [Route("api/[controller]")]
    [ApiController]
    public class CustomerController : ControllerBase
    {
        private readonly ICustomerService _customerService;
        private readonly IDocumentService _documentService;
        public CustomerController(ICustomerService customerService, IDocumentService documentService)
        {
            _customerService = customerService;
            _documentService = documentService;
        }

        [HttpGet("get")]
        public IActionResult GetAll([FromQuery]FilterParameter filterParameter)
        {
            var pagedCustomers = _customerService.GetCustomers(filterParameter);

            var metadata = new
            {
                pagedCustomers.TotalCount,
                pagedCustomers.PageSize,
                pagedCustomers.CurrentPage,
                pagedCustomers.TotalPages,
                pagedCustomers.HasNext,
                pagedCustomers.HasPrevious,
            };

            Response.Headers.Add("X-Pagination", JsonConvert.SerializeObject(metadata));

            return Ok(pagedCustomers.Items);
        }

        [HttpPost]
        public IActionResult Add(CustomerRegistrationDto customerRegisterDto)
        {
            var id = _customerService.AddCustomer(customerRegisterDto);
            var subject = "Account Created - New-Insurance";
            var body = $@"
          <p>Dear {customerRegisterDto.FirstName},</p>
          <p>Your account has been created successfully.</p>
          <p>The below are your Credentials generated by company. Use this to Login into our website.</p>
          <p>Your current Username is: <b>{customerRegisterDto.UserName}</b></p>
          <p>Your current Password is: <b>{customerRegisterDto.Password}</b></p>
          <p>If you wish to change your password, please change it after login,in the Profile Section.</p>
          <p>Looking forward to working with you. :) </p>
          <p>Best regards,<br/>New-Insurance Team</p> ";

            var emailService = new EmailService();
            emailService.SendEmail(customerRegisterDto.Email, subject, body);
            return Ok(id);
        }
        
        [HttpGet("{id}")]
        public IActionResult Get(Guid id)
        {
            var customer = _customerService.GetById(id);
            if (customer == null)
            {
                throw new CustomerNotFoundException("No such Customer Found");
            }
            return Ok(customer);
        }
        [HttpPut]
        public IActionResult Update(CustomerDto customerDto)
        {
            if (_customerService.UpdateCustomer(customerDto))
            {
                return Ok(customerDto);
            }
            return NotFound();
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(Guid id)
        {
            if (_customerService.DeleteCustomer(id))
            {
                return Ok(id);
            }
            return NotFound();
        }

        [HttpPut("changepassword")]
        public IActionResult ChangePassword(ChangePasswordDto changePasswordDto)
        {
            if (_customerService.ChangePassword(changePasswordDto))
            {
                return Ok(changePasswordDto);
            }
            return NotFound("Agent not found");
        }

        [HttpGet("GetByUserName")]
        public IActionResult GetByUserName([FromQuery] string userName)
        {
            var customer = _customerService.GetByUserName(userName);
            return Ok(new { customer });
        }

        [HttpGet("documents")]
        public IActionResult GetDocuments([FromQuery] PageParameter pageParameter, Guid customerID)
        {
            var pagedCustomers = _documentService.GetByCustomerId(pageParameter,customerID);

            var metadata = new
            {
                pagedCustomers.TotalCount,
                pagedCustomers.PageSize,
                pagedCustomers.CurrentPage,
                pagedCustomers.TotalPages,
                pagedCustomers.HasNext,
                pagedCustomers.HasPrevious,
            };

            Response.Headers.Add("X-Pagination", JsonConvert.SerializeObject(metadata));

            return Ok(pagedCustomers);

        }

        [HttpGet("complaints")]
        public IActionResult GetComplaints([FromQuery] FilterParameter filterParameter, string userName)

        {
            var user = _customerService.GetByUserName(userName);
            if (user != null)
            {
                var complaints = _customerService.GetCustomerComplaints(user.CustomerId, filterParameter);
                var metadata = new
                {
                    complaints.TotalCount,
                    complaints.PageSize,
                    complaints.CurrentPage,
                    complaints.TotalPages,
                    complaints.HasNext,
                    complaints.HasPrevious,
                };

                Response.Headers.Add("X-Pagination", JsonConvert.SerializeObject(metadata));
                return Ok(complaints);
            }
            return BadRequest("Bad request");
        }
    }
}
